### ISSUE TITLE
hp5y 2.10.* dependency

### ISSUE THREAD

**Issue by swve0869** [smistad/annotationweb#60]
Been having issues with the hp5y wheel build failing when building with python 3.9.12. Reading online that there are no build wheels for python 3.9.*  I have built with hp5y 3.0.0 and things seem to be working fine. I will report back if anything weird happens. Just letting you know cheers !

**Comment by smistad** [comment]
Thanks.
I have updated requirements.txt to specify version 3.* instead of 2.10*
